name: Build and check
on:
    push:
        branches: ["dev", "master"]
    pull_request:
        branches: ["dev", "master"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install pnpm
              uses: pnpm/action-setup@v2.2.2
              with:
                  version: 7

            - name: Use Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "pnpm"

            - name: Install build dependencies
              run: |
                  pnpm install
                  pnpm svelte-kit sync

            - name: Generate types for graphql schema
              run: pnpm houdini generate

            - name: Run eslint check
              uses: sibiraj-s/action-eslint@v2
              with:
                eslint-args: --config ./.eslintrc.cjs
                extensions: .
                github-token: ${{ secrets.GITHUB_TOKEN }}
                annotations: true

            - name: Add Svelte Check annotator
              uses: prgm-dev/svelte-check-pr-annotator@main

            - name: Run svelte-check
              run: pnpm svelte-check --tsconfig ./tsconfig.json --output machine --use-new-transformation true
